services:
  # Postgres Database (Supabase-compatible)
  db:
    image: supabase/postgres:15.1.1.78
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Next.js CMS App (development: runs "npm run dev", not production server.js)
  cms:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: ${SITE_NAME}
    ports:
      - "${PORT}:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@127.0.0.1:5432/postgres
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install && npm run dev"
volumes:
  postgres_data: