import type { Metadata } from "next";
import { Dancing_Script, Kalam } from "next/font/google";
import "./globals.css";

const kalam = Kalam({
	variable: "--font-kalam",
	subsets: ["latin"],
	weight: ["300", "400", "700"],
})

const dancingScript = Dancing_Script({
	variable: "--font-dancing-script",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body
			className={`
				${kalam.variable}
				${dancingScript.variable}
				antialiased
			`}
		>
			{children}
		</body>
		</html>
	)
}
