services:
  next-site:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    container_name: ${SITE_NAME}_dev
    command: npm run dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}